name: Docker - Setup
description: Setup Docker buildx and login if needed
inputs:
  registry:
    required: true
  push:
    required: true
  registry_token:
    description: 'Registry token for authentication'
    required: false
runs:
  using: composite
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Login (optional)
      if: ${{ inputs.push }} == 'true' && ${{ inputs.registry_token != '' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.registry_token }}
