name: Docker - Setup
description: Setup Docker buildx and login if needed
inputs:
  registry:
    required: true
  push:
    required: true
runs:
  using: composite
  steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Login (optional)
      if: ${{ inputs.push }} == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.registry_token }}
