name: Compose - Health Check
description: Wait for Docker Compose services to be healthy
inputs:
  compose_files:
    required: true
  deploy_path:
    required: true
  environment:
    required: true
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH user'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
runs:
  using: composite
  steps:
    - name: Wait for health
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa \
          -p ${{ inputs.ssh_port }} \
          ${{ inputs.ssh_user }}@${{ inputs.ssh_host }} \
          "cd ${{ inputs.deploy_path }}/${{ inputs.environment }} && \
           for i in {1..30}; do \
             if docker-compose ps | grep -q 'unhealthy'; then \
               echo 'Waiting for services...'; \
               sleep 2; \
             else \
               echo 'All services healthy'; \
               break; \
             fi; \
           done"