name: '.NET Restore Dependencies'
description: 'Restore NuGet packages with caching'

inputs:
  solution_path:
    description: 'Path to solution file'
    required: false
    default: ''
  dotnet_version:
    description: '.NET version for cache key'
    required: false
    default: '8.0.x'
  enable_caching:
    description: 'Enable NuGet package caching'
    required: false
    default: 'true'
  additional_args:
    description: 'Additional arguments for dotnet restore'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Cache NuGet packages
      if: inputs.enable_caching == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.nuget/packages
          **/obj/project.assets.json
          **/obj/*.csproj.nuget.*
        key: nuget-${{ runner.os }}-${{ inputs.dotnet_version }}-${{ hashFiles('**/*.csproj', '**/*.props', '**/*.targets') }}
        restore-keys: |
          nuget-${{ runner.os }}-${{ inputs.dotnet_version }}-
          nuget-${{ runner.os }}-

    - name: Restore dependencies
      shell: bash
      run: |
        set -euo pipefail
        
        if [ -n "${{ inputs.solution_path }}" ]; then
          dotnet restore "${{ inputs.solution_path }}" \
            --verbosity minimal \
            --configfile nuget.config \
            ${{ inputs.additional_args }}
        else
          dotnet restore \
            --verbosity minimal \
            ${{ inputs.additional_args }}
        fi