name: Deploy - SSH Setup
description: Setup SSH keys and known_hosts for deployment
inputs:
  ssh_host:
    description: 'SSH hostname or IP'
    required: true
  ssh_key:
    description: 'SSH private key'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
runs:
  using: 'composite'
  steps:
    - name: Setup SSH
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H -p "${{ inputs.ssh_port }}" ${{ inputs.ssh_host }} >> ~/.ssh/known_hosts
        echo "✅ SSH setup complete"
