name: Compose - Cleanup
description: Cleanup old Docker images and containers
inputs:
  deploy_path:
    required: true
  environment:
    required: true
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH user'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
runs:
  using: composite
  steps:
    - name: Cleanup images
      shell: bash
      run: |
        ssh -i ~/.ssh/id_rsa \
          -p ${{ inputs.ssh_port }} \
          ${{ inputs.ssh_user }}@${{ inputs.ssh_host }} \
          "docker image prune -af --filter 'until=24h' || true"